# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06d3a6550f377e4dd89f2d85345b14a05716a49ef109260521d5208ca323194df83123d4af2a16a9574c48a6a9e2b128aefc484d0719ce4d0d7b4371ca48a245

test:
  secret_key_base: 8577c3da1a17c2b85a90387cdc3233c27d8d5ec18c38036cce7e9ed47c0efe800b3e9f4a208dc7feec7b24a6fd99cee92fc2675371eb54982ffa1a775befa6e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
